# This file was generated by GoReleaser. DO NOT EDIT.
cask "laneway" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "69665a86c4edaf6a62014a0893d78d6bf86f0eb9d39fa6e84ee21a5ba5336247"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7ac7dfa0f5046e530c4e710f40c95348ce1da5f8c3e3ce202d9fd97e69a2b81"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8c15ccb6047082605ba0ee081c8f000e2700b093450934a54256aef95b1e468f"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f08246312a2bd0b724f1022579a1ce7fd093c7d802fa183abe3f9a52b6b7c54f"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_linux_amd64.tar.gz"
    end
  end

  name "laneway"
  desc "A terminal board for Jira"
  homepage "https://github.com/cornedor/laneway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "laneway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/laneway"]
    end
  end

  # No zap stanza required
end
