# This file was generated by GoReleaser. DO NOT EDIT.
cask "laneway" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "03a5349c09ade2e5b28e91c15ec83b800f30c70b4ac758d2cf9d7515f528e9a7"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5020c07c0a4ad7db99756312d1f7c9a7129140dcbab812caa33119855ffeaca"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c5c97eeddc3f9ad8287ea3d337ebc3e6a5159783afc2fd0b42876bf08114bb8c"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9aa3a5f1c6ba642f8257612e863f03192cdafbc557c4536a3eacb79144ae11cc"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_linux_amd64.tar.gz"
    end
  end

  name "laneway"
  desc "A terminal board for Jira"
  homepage "https://github.com/cornedor/laneway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "laneway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/laneway"]
    end
  end

  # No zap stanza required
end
