# This file was generated by GoReleaser. DO NOT EDIT.
cask "laneway" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "b69a17c5632179e3f2f3fcf117639d4858370ac65da45b7cd657196de6958b6c"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "73db0b7d95be9a7130c233eeb022a23beadcb63d71a2425a613006cc919668e0"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b5cdebfa0fa827cd01c68cb5dd6bb59c0b4f56eb8ea019bad7f89b641e00a907"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "397927e8b5905d5827dd8e3c7c9ae8076669202c17a3f5035c1fee4e31159843"
      url "https://github.com/cornedor/laneway/releases/download/v#{version}/laneway_#{version}_linux_amd64.tar.gz"
    end
  end

  name "laneway"
  desc "A terminal board for Jira"
  homepage "https://github.com/cornedor/laneway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "laneway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/laneway"]
    end
  end

  # No zap stanza required
end
